### ISSUE TITLE
What are the other ways to extract li_at ? 

### ISSUE THREAD

**Issue by roshangm1** [linkoutapp/linkout-scraper#10]
I am curious about what other ways are there to extract li_at so that user don't have to install chrome extension or take it from cookies ? Can the tokens that we get from "Login with Linkedin" be useful for this ?

**Comment by Sai-Adarsh** [comment]
> install chrome extension or take it from cookies

Currently we only support these two methods to get li_at. Tokens from LinkedIn social login aren't compatible at this time. It might be worth exploring whether we could introduce a social login method in the future.
