### ISSUE TITLE
Is not working?

### ISSUE THREAD

**Issue by Dante690** [linkoutapp/linkout-scraper#4]
I was trying to connect An error occurred: Pending, already connected, or weekly limit exceeded
`const Linkout = require("linkout-scraper");
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const page = await  #browser.newPage();
  const cdp = await page.target().createCDPSession();

  await page.setViewport({
    width: 1440,
    height: 900,
  });

  // add ghost-cursor for maximum safety
  await Linkout.tools.loadCursor(page, true);

  // Login with LinkedIn
  await Linkout.services.login(page, cdp, {
    cookie: LI_AT,
  });

  // Connect on LinkedIn
  await Linkout.services.connect(page, cdp, {
    message: "Hola! {{firstName}}, Espero que vaya bien el Q :) Me encantaría conectar contigo para intercambiar experiencias. Un saludo!!",
    url: "https://www.linkedin.com/in/profile/",
  });

})();`

**Comment by Sai-Adarsh** [comment]
Is your account language English? Works fine for me. Otherwise you're probably not connected or maxed out on free inmails.
