### ISSUE TITLE
Run in Docker? and other Questions...

### ISSUE THREAD

**Issue by ingeniumdesign** [linkoutapp/linkout-scraper#6]
How can I execute or integrate your script in Docker?

Can I implement the following with the tool:
Only visit users who like the hashtag XYZ?
https://www.linkedin.com/feed/hashtag/?keywords=XYZ

Does this script only work in "visit" profile mode?
Without liking, commenting etc.

Thanks

**Comment by Sai-Adarsh** [comment]
You can use this [docker image](https://github.com/linkoutapp/docker-image).

> Only visit users who like the hashtag XYZ?

You've to get a list of urls some way and run `Linkout.services.visit()` on loop (w/ random timers for max safety)

> Does this script only work in "visit" profile mode?

`Linkout.services.visit()`, yep

**Comment by ingeniumdesign** [comment]
hi and thanks.

thanks for the docker image!

sound like good for "loop (w/ random timers for max safety)" but the "User List" dont work for me, better is a way like "scan" all user from a group.
Here in this group are over 57000 users: https://www.linkedin.com/groups/3038830/
Go on the User  with a loop and random timers for visit
